defmodule PayrollApi.Pdf do
  @moduledoc """
  Minimal dependency-free PDF generator for payslips.

  Builds a valid PDF 1.4 document with text-only content. Suitable for
  simple payslip exports (no images/fonts beyond the 14 standard PDF fonts).
  """

  @doc "Generate a payslip PDF binary from a payslip result map."
  def payslip(result) do
    lines = [
      "MALAYSIA PAYROLL — PAYSLIP",
      "============================================",
      "Rates version: #{result.rates_version}",
      "Year: #{result.year}",
      "",
      "Gross wage:        RM #{fmt(result.wage)}",
      "",
      "Employee contributions:",
      "  EPF               RM #{fmt(result.employee_contributions.epf)}",
      "  SOCSO             RM #{fmt(result.employee_contributions.socso)}",
      "  EIS               RM #{fmt(result.employee_contributions.eis)}",
      "  PCB (income tax)  RM #{fmt(result.employee_contributions.pcb)}",
      "  HRDF              RM #{fmt(result.employee_contributions.hrdf)}",
      "  Total deducted:   RM #{fmt(result.employee_contributions.total)}",
      "",
      "Employer contributions:",
      "  EPF               RM #{fmt(result.employer_contributions.epf)}",
      "  SOCSO             RM #{fmt(result.employer_contributions.socso)}",
      "  EIS               RM #{fmt(result.employer_contributions.eis)}",
      "  HRDF              RM #{fmt(result.employer_contributions.hrdf)}",
      "  Total employer:   RM #{fmt(result.employer_contributions.total)}",
      "",
      "Tax details (annual):",
      "  Gross:            RM #{fmt(result.tax_details.annual_gross)}",
      "  Reliefs:          RM #{fmt(result.tax_details.annual_reliefs)}",
      "  Chargeable:       RM #{fmt(result.tax_details.annual_chargeable)}",
      "  Tax:              RM #{fmt(result.tax_details.annual_tax)}",
      "",
      "============================================",
      "NET PAY:           RM #{fmt(result.net_pay)}",
      "Total employer cost: RM #{fmt(result.total_statutory_cost)}",
      "",
      "Generated by Malaysia Payroll API"
    ]

    document(lines)
  end

  defp fmt(v) when is_number(v), do: :erlang.float_to_binary(v / 1, decimals: 2)
  defp fmt(v), do: to_string(v)

  # -- minimal PDF writer -----------------------------------------------------

  defp document(lines) do
    content =
      lines
      |> Enum.with_index()
      |> Enum.map_join("\n", fn {line, index} ->
        "BT /F1 10 Tf 50 #{760 - index * 14} Td (#{escape(line)}) Tj ET"
      end)

    objects = [
      obj(1, "<< /Type /Catalog /Pages 2 0 R >>"),
      obj(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
      obj(
        3,
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>"
      ),
      obj(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>"),
      obj(5, "<< /Length #{byte_size(content)} >>\nstream\n#{content}\nendstream")
    ]

    header = "%PDF-1.4\n%\u00e2\u00e3\u00cf\u00d3\n"
    body = Enum.join(objects, "\n") <> "\n"

    offsets = compute_offsets(header, objects)

    xref =
      "xref\n0 #{length(objects) + 1}\n0000000000 65535 f \n" <>
        Enum.map_join(offsets, "", fn off ->
          String.pad_leading(Integer.to_string(off), 10, "0") <> " 00000 n \n"
        end)

    trailer =
      "trailer\n<< /Size #{length(objects) + 1} /Root 1 0 R >>\nstartxref\n#{byte_size(header) + byte_size(body)}\n%%EOF"

    header <> body <> xref <> trailer
  end

  defp obj(num, content), do: "#{num} 0 obj\n#{content}\nendobj"

  defp compute_offsets(header, objects) do
    objects
    |> Enum.reduce({byte_size(header), []}, fn obj, {pos, acc} ->
      {pos + byte_size(obj) + 1, [pos | acc]}
    end)
    |> elem(1)
    |> Enum.reverse()
  end

  defp escape(str) do
    str
    |> String.replace("\\", "\\\\")
    |> String.replace("(", "\\(")
    |> String.replace(")", "\\)")
  end
end
